const express = require('express');
const controller = require('./product.controller');
const { requireAuth, allowRoles } = require('../../middleware/authMiddleware');
const router = express.Router();
router.get('/categories', controller.categories);
router.get('/', controller.list);
router.get('/:id', controller.detail);
router.get('/:id/recommendations', controller.recommendations);
router.post('/', requireAuth, allowRoles('ADMIN'), controller.create);
router.put('/:id', requireAuth, allowRoles('ADMIN'), controller.update);
router.delete('/:id', requireAuth, allowRoles('ADMIN'), controller.remove);
module.exports = router;
