const express = require('express');
const controller = require('./order.controller');
const { requireAuth, allowRoles } = require('../../middleware/authMiddleware');
const router = express.Router();
router.post('/', requireAuth, allowRoles('CUSTOMER'), controller.create);
router.get('/my', requireAuth, allowRoles('CUSTOMER'), controller.my);
router.get('/admin/all', requireAuth, allowRoles('ADMIN','STAFF'), controller.all);
router.get('/:id', requireAuth, controller.detail);
router.patch('/:id/status', requireAuth, allowRoles('ADMIN','STAFF'), controller.updateStatus);
module.exports = router;
